name: Build

on: [push]

env:
  is_tag: ${{ startsWith(github.ref, 'refs/tags/') }}

  PROJECT_FILE_PATH: vs-frameblender.sln

  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # install cuda
      - uses: Jimver/cuda-toolkit@v0.2.18
        id: cuda-toolkit

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: MSBuild /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_PLATFORM }} ${{ env.PROJECT_FILE_PATH }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: vs-frameblender
          path: |
            bin/release/x64/vs-frameblender-x64.dll

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ env.is_tag == 'true' }}
        with:
          files: |
            bin/release/x64/vs-frameblender-x64.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
